source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

inhibit_all_warnings!
use_frameworks!

target 'WannaSDKExample CocoaPods' do
  pod 'WannaSDK'
  pod 'WannaSDKToolkit', :path => '../WannaSDKToolkit/WannaSDKToolkit.podspec'
  pod 'WannaTryOn', :path => '../WannaTryOn/WannaTryOn.podspec'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
