source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:WANNABY/ios-specs-internal.git'

platform :ios, '11.0'

inhibit_all_warnings!
use_frameworks!

target 'WannaSDK_Example' do
  pod 'WannaSDK', '~> 6.0.0'
end
